version : '3'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: on-failure
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  nginx:
    build: ./requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    # tty: true
    # stdin_open: true 

  wordpress:
    build: ./requirements/wordpress
    restart: on-failure
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    # tty: true
    # stdin_open: true 

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jeokim/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver_opts:
      device: /home/jeokim/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge
